import graphviz
import pandas as pd

map = graphviz.Digraph(comment='Metro de Madrid')
files = pd.read_csv('')

def linea1(map):

    map.node('Pinar de Chamartín')
    map.node('Bambú')
    map.node('Chamartín')
    map.node('Plaza de Castilla')
    map.node('Valdeacederas')
    map.node('Tetuán')
    map.node('Estrecho')
    map.node('Alvarado')
    map.node('Cuatro caminos')
    map.node('Ríos rosas')
    map.node('Iglesias')
    map.node('Bilbao')
    map.node('Tribunal')
    map.node('Gran Vía')
    map.node('Sol')
    map.node('Tirso de Molina')
    map.node('Antón Martín')
    map.node('Estación del Arte')
    map.node('Atocha')
    map.node('Menéndez Pelayo')
    map.node('Pacífico')
    map.node('Puente de Vallecas')
    map.node('Nueva Numancia')
    map.node('Portazgo')
    map.node('Buenos Aires')
    map.node('Alto del Arenal')
    map.node('Miguel Hernández')
    map.node('Sierra de Guadalupe')
    map.node('Villa de Vallecas')
    map.node('Congosto')
    map.node('La Gavia')
    map.node('Valdecarros')

def linea2(map):
    map.node('Las Rosas')
    map.node('Avenida de Guadalajara')
    map.node('Alsacia')
    map.node('La Almudena')
    map.node('La Elipa')
    map.node('Ventas')
    map.node('Manuel Becerra')
    map.node('Goya')
    map.node('Príncipe de Vergara')
    map.node('Retiro')
    map.node('Banco de España')
    map.node('Sevilla')
    map.node('Sol')
    map.node('Ópera')
    map.node('Santo Domingo')
    map.node('Noviciado')
    map.node('San Bernardo')
    map.node('Quevedo')
    map.node('Canal')
    map.node('Cuatro Caminos')

def linea3(map):
    map.node('Villaverde Alto')
    map.node('San Cristóbal')
    map.node('Villaverde Bajo-Cruce')
    map.node('Ciudad de los Ángeles')
    map.node('San Fermín-Orcasur')
    map.node('Hospital 12 de Octubre')
    map.node('Almendrales')
    map.node('Legazpi')
    map.node('Delicias')
    map.node('Palos de la Frontera')
    map.node('Embajadores')
    map.node('Lavapiés')
    map.node('Sol')
    map.node('Callao')
    map.node('Plaza de España')
    map.node('Ventura Rodríguez')
    map.node('Argüelles')
    map.node('Moncloa')

def linea4(map):
    map.node('Argüelles')
    map.node('San Bernardo')
    map.node('Bilbao')
    map.node('Alonso Martínez')
    map.node('Colón')
    map.node('Serrano')
    map.node('Velázquez')
    map.node('Goya')
    map.node('Lista')
    map.node('Diego de León')
    map.node('Avenida de América')
    map.node('Prosperidad')
    map.node('Alfonso XIII')
    map.node('Avenida de la Paz')
    map.node('Arturo Soria')
    map.node('Esperanza')
    map.node('Canillas')
    map.node('Mar de Cristal')
    map.node('San Lorenzo')
    map.node('Parque de Santa María')
    map.node('Hortaleza')
    map.node('Manoteras')
    map.node('Pinar de Chamartín')

def linea5(map):
    map.node('Alameda de Osuna')
    map.node('El Capricho')
    map.node('Canillejas')
    map.node('Torre Arias')
    map.node('Suanzes')
    map.node('Ciudad Lineal')
    map.node('Pueblo Nuevo')
    map.node('Quintana')
    map.node('El Carmen')
    map.node('Ventas')
    map.node('Diego de León')
    map.node('Núñez de Balboa')
    map.node('Rubén Darío')
    map.node('Alonso Martínez')
    map.node('Chueca')
    map.node('Gran Vía')
    map.node('Callao')
    map.node('Ópera')
    map.node('La Latina')
    map.node('Puerta de Toledo')
    map.node('Acacias')
    map.node('Pirámides')
    map.node('Marqués de Vadillo')
    map.node('Urgel')
    map.node('Oporto')
    map.node('Vista Alegre')
    map.node('Carabanchel')
    map.node('Eugenia de Montijo')
    map.node('Aluche')
    map.node('Empalme')
    map.node('Campamento')
    map.node('Casa de Campo')

def linea6(map):
    map.node('Laguna')
    map.node('Carpetana')
    map.node('Oporto')
    map.node('Opañel')
    map.node('Plaza Elíptica')
    map.node('Usera')
    map.node('Legazpi')
    map.node('Arganzuela-Planetario')
    map.node('Méndez Álvaro')
    map.node('Pacífico')
    map.node('Conde de Casal')
    map.node('Sainz de Baranda')
    map.node('O\'Donnell')
    map.node('Manuel Becerra')
    map.node('Diego de León')
    map.node('Avenida de América')
    map.node('República Argentina')
    map.node('Nuevos Ministerios')
    map.node('Cuatro Caminos')
    map.node('Guzmán el Bueno')
    map.node('Vicente Aleixandre')
    map.node('Ciudad Universitaria')
    map.node('Moncloa')
    map.node('Argüelles')
    map.node('Príncipe Pío')
    map.node('Puerta del Ángel')
    map.node('Alto de Extremadura')
    map.node('Lucero')
    map.node('Laguna')

def linea7(map):
    map.node('Hospital del Henares')
    map.node('Henares')
    map.node('Jarama')
    map.node('San Fernando')
    map.node('La Rambla')
    map.node('Coslada Central')
    map.node('Barrio del Puerto')
    map.node('Estadio Metropolitano')
    map.node('Las Musas')
    map.node('San Blas')
    map.node('Simancas')
    map.node('García Noblejas')
    map.node('Ascao')
    map.node('Pueblo Nuevo')
    map.node('Barrio de la Concepción')
    map.node('Parque de las Avenidas')
    map.node('Cartagena')
    map.node('Avenida de América')
    map.node('Gregorio Marañón')
    map.node('Alonso Cano')
    map.node('Canal')
    map.node('Islas Filipinas')
    map.node('Guzmán el Bueno')
    map.node('Francos Rodríguez')
    map.node('Valdezarza')
    map.node('Antonio Machado')
    map.node('Peñagrande')
    map.node('Avenida de la Ilustración')
    map.node('Lacoma')
    map.node('Arroyofresno')
    map.node('Pitis')

def linea8(map):
    map.node('Nuevos Ministerios')
    map.node('Colombia')
    map.node('Pinar del Rey')
    map.node('Mar de Cristal')
    map.node('Feria de Madrid')
    map.node('Aeropuerto T1-T2-T3')
    map.node('Barajas')
    map.node('Aeropuerto T4')

def linea9(map):
    map.node('Paco de Lucía')
    map.node('Mirasierra')
    map.node('Herrera Oria')
    map.node('Barrio del Pilar')
    map.node('Ventilla')
    map.node('Plaza de Castilla')
    map.node('Duque de Pastrana')
    map.node('Pío XII')
    map.node('Colombia')
    map.node('Concha Espina')
    map.node('Cruz del Rayo')
    map.node('Avenida de América')
    map.node('Núñez de Balboa')
    map.node('Príncipe de Vergara')
    map.node('Ibiza')
    map.node('Sainz de Baranda')
    map.node('Estrella')
    map.node('Vinateros')
    map.node('Artilleros')
    map.node('Pavones')
    map.node('Valdebernardo')
    map.node('Vicálvaro')
    map.node('San Cipriano')
    map.node('Puerta de Arganda')
    map.node('Rivas Urbanizaciones')
    map.node('Rivas Futura')
    map.node('Rivas Vaciamadrid')
    map.node('La Poveda')
    map.node('Arganda del Rey')

def linea10(map):
    map.node('Hospital Infanta Sofía')
    map.node('Reyes Católicos')
    map.node('Baunatal')
    map.node('Manuel de Falla')
    map.node('Marqués de la Valdavia')
    map.node('La Moraleja')
    map.node('La Granja')
    map.node('Ronda de la Comunicación')
    map.node('Tres Olivos')
    map.node('Fuencarral')
    map.node('Begoña')
    map.node('Chamartín')
    map.node('Plaza de Castilla')
    map.node('Cuzco')
    map.node('Santiago Bernabéu')
    map.node('Nuevos Ministerios')
    map.node('Gregorio Marañón')
    map.node('Alonso Martínez')
    map.node('Tribunal')
    map.node('Plaza de España')
    map.node('Príncipe Pío')
    map.node('Lago')
    map.node('Batán')
    map.node('Casa de Campo')
    map.node('Colonia Jardín')
    map.node('Aviación Española')
    map.node('Cuatro Vientos')
    map.node('Joaquín Vilumbrales')
    map.node('Puerta del Sur')

def linea11(map):
    map.node('Plaza Elíptica')
    map.node('Abrantes')
    map.node('Pan Bendito')
    map.node('San Francisco')
    map.node('Carabanchel Alto')
    map.node('La Peseta')
    map.node('La Fortuna')

def linea12(map):
    map.node('Puerta del Sur')
    map.node('Parque Lisboa')
    map.node('Alcorcón Central')
    map.node('Parque Oeste')
    map.node('Universidad Rey Juan Carlos')
    map.node('Móstoles Central')
    map.node('Pradillo')
    map.node('Hospital de Móstoles')
    map.node('Manuela Malasaña')
    map.node('Loranca')
    map.node('Hospital de Fuenlabrada')
    map.node('Parque Europa')
    map.node('Fuenlabrada Central')
    map.node('Parque de los Estados')
    map.node('Arroyo Culebro')
    map.node('Conservatorio')
    map.node('Alonso de Mendoza')
    map.node('Getafe Central')
    map.node('Juan de la Cierva')
    map.node('El Casar')
    map.node('Los Espartales')
    map.node('El Bercial')
    map.node('El Carrascal')
    map.node('Julián Besteiro')
    map.node('Casa del Reloj')
    map.node('Hospital Severo Ochoa')
    map.node('Leganés Central')
    map.node('San Nicasio')
    map.node('Puerta del Sur')

def lineaR(map):
    map.node('Ópera')
    map.node('Príncipe Pío')
